import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
function load(){const window={};const context=vm.createContext({window,structuredClone,console,globalThis:null,Date});context.globalThis=context;for(const file of ['../engine/record-store-engine.js','../emojeo-emoji-record.js','../emojeo-unicode-catalog.js'])vm.runInContext(fs.readFileSync(new URL(file,import.meta.url),'utf8'),context,{filename:file});return{catalog:context.emojeoUnicodeCatalog,model:context.emojeoEmojiRecord}}
const sample=`# emoji-test.txt\n# Date: 2026-04-30, 22:40:18 GMT\n# Version: 18.0\n# group: Smileys & Emotion\n# subgroup: face-smiling\n1F600 ; fully-qualified # 😀 E1.0 grinning face\n# subgroup: face-affection\n263A FE0F ; fully-qualified # ☺️ E0.6 smiling face\n263A ; unqualified # ☺ E0.6 smiling face\n# group: Component\n# subgroup: skin-tone\n1F3FB ; component # 🏻 E1.0 light skin tone\n`;
test('Unicode catalog pins the official Unicode Emoji 18.0 production data',()=>{const {catalog}=load();assert.equal(catalog.SOURCE.version,'18.0');assert.equal(Object.hasOwn(catalog.SOURCE,'expectedRgiCount'),false);assert.match(catalog.SOURCE.url,/unicode\.org\/Public\/18\.0\.0\/emoji\/emoji-test\.txt/)});
test('Unicode emoji-test parser preserves official group, subgroup, order and qualification',()=>{const {catalog}=load();const p=catalog.parse(sample);assert.equal(p.version,'18.0');assert.equal(p.rows.length,4);assert.equal(p.rows[0].group,'Smileys & Emotion');assert.equal(p.rows[1].subgroup,'face-affection');assert.equal(p.rows[2].status,'unqualified')});
test('catalog creates records only for the RGI union and attaches non-RGI presentation forms as variants',()=>{const {catalog}=load();const records=catalog.buildRecords(catalog.parse(sample));assert.equal(records.length,3);const smile=records.find(r=>r.names.cldr==='smiling face');assert.equal(smile.glyph,'☺️');assert.equal(smile.presentation.variants.length,1);assert.equal(smile.presentation.variants[0].qualification,'unqualified');assert.equal(records.some(r=>r.glyph==='☺'),false)});
test('catalog import persists official source provenance without adding interpretive tags',async()=>{const {catalog,model}=load();const store=model.createStore();await store.initialize();const records=catalog.buildRecords(catalog.parse(sample));const result=await catalog.importIntoStore(store,records);assert.equal(result.imported,3);const saved=store.all()[0];assert.equal(saved.provenance.source,'Unicode Consortium');assert.equal(Object.hasOwn(saved.data,'tags'),false)});
test('official source loader accepts injected fetch for deterministic/offline tests',async()=>{const {catalog}=load();const fetchImpl=async()=>({ok:true,text:async()=>sample});const loaded=await catalog.loadOfficial({fetchImpl});assert.equal(loaded.parsed.version,'18.0');assert.equal(loaded.records.length,3)});
