import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
function load(){const ctx={structuredClone,Date,Map,Set,console};ctx.globalThis=ctx;ctx.window=ctx;vm.createContext(ctx);vm.runInContext(fs.readFileSync('emojeo-mosaic-review.js','utf8'),ctx);return ctx.emojeoMosaicReview;}
const candidate=()=>({id:'cluster-1',kind:'mosaic-candidate',canonical:false,advisory:true,decisionRequired:true,subjects:[{type:'emoji',id:'a',emoji:'😀'},{type:'emoji',id:'b',emoji:'😃'}],commonTraits:[{type:'emojeo-trait',id:'happy',label:'Happy'}]});
test('review board imports advisory Mosaic candidates without promoting them',()=>{const b=load().createReviewBoard({candidates:[candidate()]});const r=b.get('cluster-1');assert.equal(r.status,'proposed');assert.equal(r.canonicalMosaic,null)});
test('algorithmic or nonhuman approval is refused',()=>{const b=load().createReviewBoard({candidates:[candidate()]});assert.throws(()=>b.decide('cluster-1','approved',{human:false}),/human decision/)});
test('human can reject a candidate without deleting discovery evidence',()=>{const b=load().createReviewBoard({candidates:[candidate()]});const r=b.decide('cluster-1','rejected',{human:true,decidedBy:'curator',rationale:'not useful'});assert.equal(r.status,'rejected');assert.equal(r.candidate.id,'cluster-1');assert.equal(r.canonicalMosaic,null)});
test('materialization is impossible before explicit approval',()=>{const b=load().createReviewBoard({candidates:[candidate()]});assert.throws(()=>b.materialize('cluster-1',{name:'Smiles'}),/human-approved/)});
test('human-approved candidate can become a named canonical Mosaic',()=>{const b=load().createReviewBoard({candidates:[candidate()]});b.decide('cluster-1','approved',{human:true,decidedBy:'Billy',rationale:'useful grouping',at:'2026-09-20T00:00:00Z'});const m=b.materialize('cluster-1',{name:'Smiles',description:'Two smiles',gem:{id:'gem-smiles'}});assert.equal(m.kind,'mosaic');assert.equal(m.status,'canonical');assert.equal(m.name,'Smiles');assert.equal(m.emoji.length,2);assert.equal(m.sourceCandidateId,'cluster-1');assert.equal(m.decision.human,true);assert.equal(m.gem.id,'gem-smiles')});
test('review snapshot makes the human canon boundary explicit',()=>{const b=load().createReviewBoard({candidates:[candidate()]});const p=b.snapshot().policy;assert.equal(p.discoveryIsAdvisory,true);assert.equal(p.humanApprovalRequired,true);assert.equal(p.materializationRequiresApproval,true)});
