import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
function load(){const ctx={structuredClone,Date,Map,Set,console};ctx.globalThis=ctx;ctx.window=ctx;vm.createContext(ctx);vm.runInContext(fs.readFileSync('emojeo-design-graph.js','utf8'),ctx);return ctx.emojeoDesignGraph;}
test('Pass 10 begins with emoji and Mosaic but permits new design domains',()=>{const g=load().createDesignGraph();assert.ok(g.snapshot().types.some(t=>t.id==='emoji'));assert.ok(g.snapshot().types.some(t=>t.id==='mosaic'));g.registerType({id:'gem',label:'Gem'});assert.equal(g.snapshot().types.some(t=>t.id==='gem'),true)});
test('arbitrary design Things can coexist in one graph',()=>{const g=load().createDesignGraph({types:[{id:'gem'},{id:'setting'}]});g.createThing({type:'gem',id:'moon',name:'Moon Gem'});g.createThing({type:'setting',id:'night',name:'Night'});assert.equal(g.listThings().length,2)});
test('relationship vocabulary is extensible and type constrained',()=>{const g=load().createDesignGraph({types:[{id:'gem'},{id:'setting'}],relationshipTypes:[{id:'unlocks',fromTypes:['gem'],toTypes:['setting']}]});g.createThing({type:'gem',id:'g'});g.createThing({type:'setting',id:'s'});g.relate({type:'unlocks',from:{type:'gem',id:'g'},to:{type:'setting',id:'s'},advisory:false,humanApproved:true});assert.equal(g.neighbors('gem','g')[0]?.thing?.id,'s')});
test('machine-like connections default to advisory',()=>{const g=load().createDesignGraph({types:[{id:'gem'}],relationshipTypes:[{id:'related'}]});g.createThing({type:'gem',id:'a'});g.createThing({type:'gem',id:'b'});const r=g.relate({type:'related',from:{type:'gem',id:'a'},to:{type:'gem',id:'b'}});assert.equal(r.advisory,true);assert.equal(r.humanApproved,false)});
test('canonical connections require explicit human approval',()=>{const g=load().createDesignGraph({types:[{id:'gem'}],relationshipTypes:[{id:'related'}]});g.createThing({type:'gem',id:'a'});g.createThing({type:'gem',id:'b'});assert.throws(()=>g.relate({type:'related',from:{type:'gem',id:'a'},to:{type:'gem',id:'b'},advisory:false}),/human approval/)});
test('emoji records bridge into the multi-domain graph as authoritative Things',()=>{const g=load().createDesignGraph();const e=g.importEmoji({id:'U+1F600',glyph:'😀',names:{cldr:'grinning face'},taxonomy:{group:'Smileys & Emotion',subgroup:'face-smiling'}});assert.equal(e.type,'emoji');assert.equal(e.authority,'authoritative');assert.equal(e.metadata.unicodeGroup,'Smileys & Emotion')});
test('human-approved Mosaic imports connect existing emoji members',()=>{const g=load().createDesignGraph();g.importEmoji({id:'a',glyph:'😀',names:{cldr:'a'},taxonomy:{}});g.importEmoji({id:'b',glyph:'😃',names:{cldr:'b'},taxonomy:{}});g.importMosaic({id:'mosaic-smiles',name:'Smiles',status:'canonical',emoji:[{id:'a'},{id:'b'}],decision:{human:true}});assert.equal(g.neighbors('mosaic','mosaic-smiles').length,2);assert.equal(g.listRelationships()[0].humanApproved,true)});
test('graph can surface disconnected design Things',()=>{const g=load().createDesignGraph({types:[{id:'gem'}]});g.createThing({type:'gem',id:'unused'});assert.equal(g.disconnected({type:'gem'})[0].id,'unused')});
test('graph traversal follows connections across domains',()=>{const g=load().createDesignGraph({types:[{id:'gem'},{id:'setting'}],relationshipTypes:[{id:'awards',fromTypes:['mosaic'],toTypes:['gem']},{id:'unlocks',fromTypes:['gem'],toTypes:['setting']}]});g.createThing({type:'mosaic',id:'m'});g.createThing({type:'gem',id:'g'});g.createThing({type:'setting',id:'s'});g.relate({type:'awards',from:{type:'mosaic',id:'m'},to:{type:'gem',id:'g'},advisory:false,humanApproved:true});g.relate({type:'unlocks',from:{type:'gem',id:'g'},to:{type:'setting',id:'s'},advisory:false,humanApproved:true});const rows=g.traverse('mosaic','m',{maxDepth:2});assert.equal(rows.length,2);assert.equal(rows[1].thing.id,'s')});
