import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
function load(){const ctx={structuredClone,Date,Map,Set,console};ctx.globalThis=ctx;ctx.window=ctx;vm.createContext(ctx);for(const f of ['emojeo-design-graph.js','emojeo-design-catalog.js','emojeo-canon-ledger.js'])vm.runInContext(fs.readFileSync(f,'utf8'),ctx);const g=ctx.emojeoDesignGraph.createDesignGraph();ctx.emojeoDesignCatalog.installDesignCatalog(g);const l=ctx.emojeoCanonLedger.createCanonLedger(g);return {g,l,c:ctx.emojeoDesignCatalog};}
test('Pass 12 ledger attaches claims to any catalog Thing',()=>{const {g,l,c}=load();c.createCatalogThing(g,{type:'setting',id:'s'});const x=l.assertClaim({subject:{type:'setting',id:'s'},field:'unlock',value:'gem-x',state:'proposed'});assert.equal(x.field,'unlock')});
test('claims cannot attach to nonexistent Things',()=>{const {l}=load();assert.throws(()=>l.assertClaim({subject:{type:'gem',id:'missing'},field:'x',value:1}),/must already exist/)});
test('machine or curated claims cannot silently become current canon',()=>{const {g,l,c}=load();c.createCatalogThing(g,{type:'item',id:'i'});assert.throws(()=>l.assertClaim({subject:{type:'item',id:'i'},field:'role',value:'x',state:'current',authority:'discovered'}),/requires human-canon or authoritative/)});
test('human canon can establish a current design fact',()=>{const {g,l,c}=load();c.createCatalogThing(g,{type:'gem',id:'g'});const x=l.assertClaim({subject:{type:'gem',id:'g'},field:'color',value:'blue',state:'current',authority:'human-canon'});assert.equal(x.state,'current')});
test('historical claims remain preserved beside current claims',()=>{const {g,l,c}=load();c.createCatalogThing(g,{type:'mosaic',id:'m'});l.assertClaim({subject:{type:'mosaic',id:'m'},field:'award',value:'room',state:'historical'});l.assertClaim({subject:{type:'mosaic',id:'m'},field:'award',value:'tchotchke',state:'current',authority:'human-canon'});assert.equal(l.listClaims({subject:{type:'mosaic',id:'m'},field:'award'}).length,2)});
test('conflict detection surfaces incompatible live claims instead of choosing one',()=>{const {g,l,c}=load();c.createCatalogThing(g,{type:'npc',id:'n'});l.assertClaim({subject:{type:'npc',id:'n'},field:'location',value:'cafe',state:'proposed'});l.assertClaim({subject:{type:'npc',id:'n'},field:'location',value:'bookshop',state:'proposed'});assert.equal(l.conflicts().length,1)});
test('claim lifecycle supports explicit retirement without deletion',()=>{const {g,l,c}=load();c.createCatalogThing(g,{type:'reward',id:'r'});const x=l.assertClaim({subject:{type:'reward',id:'r'},field:'source',value:'event',state:'proposed'});l.transition(x.id,'retired');assert.equal(l.getClaim(x.id).state,'retired')});
test('current view refuses to collapse contradictory current canon',()=>{const {g,l,c}=load();c.createCatalogThing(g,{type:'setting',id:'s'});l.assertClaim({subject:{type:'setting',id:'s'},field:'theme',value:'a',state:'current',authority:'human-canon'});l.assertClaim({subject:{type:'setting',id:'s'},field:'theme',value:'b',state:'current',authority:'human-canon'});const v=l.currentView({type:'setting',id:'s'});assert.equal(v.unresolved.length,1);assert.equal(Object.hasOwn(v.fields,'theme'),false)});
