import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
const root=new URL('../',import.meta.url),ctx=vm.createContext({structuredClone,console,Date});for(const f of ['emojeo-design-graph.js','emojeo-design-catalog.js','emojeo-canon-ledger.js','emojeo-design-recovery.js'])vm.runInContext(fs.readFileSync(new URL(f,root),'utf8'),ctx);
function setup(storage=null){const graph=ctx.emojeoDesignGraph.createDesignGraph();ctx.emojeoDesignCatalog.installDesignCatalog(graph);graph.createThing({type:'gem',id:'ruby',name:'Ruby',authority:'human-canon'});graph.createThing({type:'setting',id:'cellar',name:'Color Cellar',authority:'human-canon'});graph.relate({type:'associated-with',from:{type:'gem',id:'ruby'},to:{type:'setting',id:'cellar'},advisory:false,humanApproved:true});const ledger=ctx.emojeoCanonLedger.createCanonLedger(graph);ledger.assertClaim({subject:{type:'gem',id:'ruby'},field:'unlock',value:'cellar',state:'current',authority:'human-canon'});return {graph,ledger,recovery:ctx.emojeoDesignRecovery.createDesignRecovery({graph,ledger,storage,graphApi:ctx.emojeoDesignGraph,ledgerApi:ctx.emojeoCanonLedger})}}
test('checkpoint captures graph and canon without mutating either',()=>{const {graph,ledger,recovery}=setup(),before=JSON.stringify(graph.snapshot())+JSON.stringify(ledger.snapshot()),c=recovery.createCheckpoint({label:'Known good'});assert.equal(c.payload.graph.things.length,2);assert.equal(c.payload.canon.claims.length,1);assert.equal(JSON.stringify(graph.snapshot())+JSON.stringify(ledger.snapshot()),before)});
test('checkpoint checksum detects tampering',()=>{const {recovery}=setup(),c=recovery.createCheckpoint();assert.equal(recovery.verify(c).valid,true);c.payload.graph.things[0].name='Tampered';assert.equal(recovery.verify(c).valid,false)});
test('portable export and import preserve verified checkpoint',()=>{const a=setup().recovery,c=a.createCheckpoint({reason:'handoff'}),text=a.exportCheckpoint(c.id),b=setup().recovery,copy=b.importCheckpoint(text);assert.equal(b.verify(copy).valid,true);assert.equal(copy.reason,'handoff')});
test('recovery plan previews exact restored counts and promises no live overwrite',()=>{const {recovery}=setup(),c=recovery.createCheckpoint(),p=recovery.recoveryPlan(c.id);assert.equal(p.counts.things,2);assert.equal(p.counts.claims,1);assert.equal(p.willOverwriteLiveState,false);assert.equal(p.requiresExplicitApproval,true)});
test('restore requires explicit approval and identified human',()=>{const {recovery}=setup(),c=recovery.createCheckpoint();assert.throws(()=>recovery.restoreFresh(c.id),/explicit human approval/);assert.throws(()=>recovery.restoreFresh(c.id,{approved:true}),/explicit human approval/)});
test('approved recovery reconstructs fresh graph and canon while leaving live state alone',()=>{const {graph,recovery}=setup(),c=recovery.createCheckpoint(),before=JSON.stringify(graph.snapshot()),out=recovery.restoreFresh(c.id,{approved:true,actor:'Billy'});assert.notEqual(out.graph,graph);assert.equal(out.graph.getThing('gem','ruby').name,'Ruby');assert.equal(out.graph.listRelationships().length,1);assert.equal(out.ledger.currentView({type:'gem',id:'ruby'}).fields.unlock,'cellar');assert.equal(JSON.stringify(graph.snapshot()),before);assert.equal(out.audit.overwroteLiveState,false)});
test('storage save/load round-trip is explicit and checksum verified',()=>{const mem=new Map(),storage={setItem:(k,v)=>mem.set(k,v),getItem:k=>mem.get(k)||null};const {recovery}=setup(storage),c=recovery.createCheckpoint(),saved=recovery.save(c.id,'safe');assert.ok(saved.bytes>0);const loaded=recovery.load('safe');assert.equal(recovery.verify(loaded).valid,true)});
