import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
const root=new URL('../',import.meta.url);const ctx=vm.createContext({structuredClone,console});for(const f of ['emojeo-design-graph.js','emojeo-design-catalog.js','emojeo-canon-ledger.js','emojeo-progression-analysis.js','emojeo-design-health.js','emojeo-change-impact.js','emojeo-decision-workspace.js','emojeo-design-change-application.js'])vm.runInContext(fs.readFileSync(new URL(f,root),'utf8'),ctx);
function setup(change={kind:'retire-thing',subject:{type:'gem',id:'g1'}}){const graph=ctx.emojeoDesignGraph.createDesignGraph();ctx.emojeoDesignCatalog.installDesignCatalog(graph);graph.createThing({type:'gem',id:'g1',name:'Gem'});graph.createThing({type:'setting',id:'s1',name:'Setting'});graph.relate({type:'unlocks',from:{type:'gem',id:'g1'},to:{type:'setting',id:'s1'},advisory:false,humanApproved:true});const ledger=ctx.emojeoCanonLedger.createCanonLedger(graph);const progression=ctx.emojeoProgressionAnalysis.createProgressionAnalysis({graph});const health=ctx.emojeoDesignHealth.createDesignHealth({graph,catalog:ctx.emojeoDesignCatalog,progression,ledger});const impact=ctx.emojeoChangeImpact.createChangeImpact({graph,ledger,progression,health});const workspace=ctx.emojeoDecisionWorkspace.createDecisionWorkspace({impact});const d=workspace.create({title:'Change',change});workspace.submit(d.id,{actor:'Billy'});workspace.decide(d.id,{approved:true,actor:'Billy'});const plan=workspace.implementationPlan(d.id);const app=ctx.emojeoDesignChangeApplication.createDesignChangeApplication({graph,ledger,impact,workspace});return {graph,ledger,impact,workspace,plan,app}}
test('preview is exact and non-mutating',()=>{const {graph,ledger,plan,app}=setup();const g=JSON.stringify(graph.snapshot()),l=JSON.stringify(ledger.snapshot());const p=app.preview(plan);assert.equal(p.policy.previewOnly,true);assert.equal(p.operations[0].after.status,'retired');assert.equal(JSON.stringify(graph.snapshot()),g);assert.equal(JSON.stringify(ledger.snapshot()),l)});
test('apply requires identified human and marks decision implemented',()=>{const {graph,workspace,plan,app}=setup();assert.throws(()=>app.apply(plan,{actor:'system'}));const tx=app.apply(plan,{actor:'Billy'});assert.equal(tx.state,'applied');assert.equal(graph.getThing('gem','g1').status,'retired');assert.equal(workspace.get(plan.decisionId).state,'implemented')});
test('stale plan is rejected',()=>{const {graph,plan,app}=setup();graph.createThing({type:'gem',id:'g1',name:'Gem changed'});assert.throws(()=>app.apply(plan,{actor:'Billy'}),/stale/)});
test('claim change supersedes current claim and undo restores exact prior claim',()=>{const change={kind:'change-claim',subject:{type:'gem',id:'g1'},field:'color',value:'red'};const {ledger,plan,app}=setup(change);const old=ledger.assertClaim({id:'old-color',subject:{type:'gem',id:'g1'},field:'color',value:'blue',state:'current',authority:'human-canon',provenance:{source:'Billy'}});/* plan predates this claim, so regenerate decision */assert.throws(()=>app.apply(plan,{actor:'Billy'}),/stale/);});
test('fresh claim change applies and undo restores prior canon',()=>{const base=setup();base.ledger.assertClaim({id:'old-color',subject:{type:'gem',id:'g1'},field:'color',value:'blue',state:'current',authority:'human-canon',provenance:{source:'Billy'}});const change={kind:'change-claim',subject:{type:'gem',id:'g1'},field:'color',value:'red'};const d=base.workspace.create({title:'Color',change});base.workspace.submit(d.id,{actor:'Billy'});base.workspace.decide(d.id,{approved:true,actor:'Billy'});const plan=base.workspace.implementationPlan(d.id);const tx=base.app.apply(plan,{actor:'Billy'});assert.equal(base.ledger.currentView({type:'gem',id:'g1'}).fields.color,'red');base.app.undo(tx.id,{actor:'Billy'});assert.equal(base.ledger.getClaim('old-color').state,'current');assert.equal(base.ledger.currentView({type:'gem',id:'g1'}).fields.color,'blue')});
test('connection add and remove are transactional and undoable',()=>{const b=setup();const add={kind:'add-connection',subject:{type:'gem',id:'g1'},relationship:{id:'new-link',type:'unlocks',from:{type:'gem',id:'g1'},to:{type:'setting',id:'s1'}}};const d=b.workspace.create({title:'Add',change:add});b.workspace.submit(d.id,{actor:'Billy'});b.workspace.decide(d.id,{approved:true,actor:'Billy'});const tx=b.app.apply(b.workspace.implementationPlan(d.id),{actor:'Billy'});assert.ok(b.graph.getRelationship('new-link'));b.app.undo(tx.id,{actor:'Billy'});assert.equal(b.graph.getRelationship('new-link'),null)});
