import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
function load(){const ctx={structuredClone,Date,Map,Set,console};ctx.globalThis=ctx;ctx.window=ctx;vm.createContext(ctx);for(const f of ['emojeo-design-graph.js','emojeo-design-catalog.js','emojeo-canon-ledger.js','emojeo-evidence-intake.js'])vm.runInContext(fs.readFileSync(f,'utf8'),ctx);const g=ctx.emojeoDesignGraph.createDesignGraph();const c=ctx.emojeoDesignCatalog;c.installDesignCatalog(g);const l=ctx.emojeoCanonLedger.createCanonLedger(g);return {g,c,l,i:ctx.emojeoEvidenceIntake.createEvidenceIntake({graph:g,catalog:c,ledger:l})};}
test('Pass 13 stages recovered evidence without mutating design graph',()=>{const {g,i}=load();i.stage({source:{id:'recovery'},items:[{kind:'thing',payload:{type:'gem',id:'g'}}]});assert.equal(g.listThings({type:'gem'}).length,0)});
test('intake requires source provenance',()=>{const {i}=load();assert.throws(()=>i.stage({items:[]}),/source provenance/)});
test('preview reports mixed evidence before commit',()=>{const {i}=load();const b=i.stage({source:{locator:'doc:1'},items:[{kind:'thing',payload:{type:'gem',id:'g'}},{kind:'claim',payload:{subject:{type:'gem',id:'g'},field:'x',value:1}}]});const p=i.preview(b.id);assert.equal(p.total,2);assert.equal(p.counts.claim,1)});
test('duplicate evidence within one source batch is collapsed',()=>{const {i}=load();const x={kind:'thing',payload:{type:'gem',id:'g'}};const b=i.stage({source:{id:'s'},items:[x,x]});assert.equal(b.items.length,1)});
test('commit cannot occur without explicit human approval',()=>{const {i}=load();const b=i.stage({source:{id:'s'},items:[]});assert.throws(()=>i.commit(b.id),/explicit human approval/)});
test('approved intake creates Things and preserves source provenance',()=>{const {g,i}=load();const b=i.stage({source:{id:'ledger-1200',locator:'REC-0042'},items:[{kind:'thing',payload:{type:'setting',id:'annex',name:'Annex'}}]});i.commit(b.id,{humanApproved:true,reviewer:'human'});const t=g.getThing('setting','annex');assert.equal(t.name,'Annex');assert.equal(t.provenance.intakeBatchId,b.id)});
test('approved intake can establish explicit current human canon claims',()=>{const {l,i}=load();const b=i.stage({source:{id:'canon-note'},items:[{kind:'thing',payload:{type:'item',id:'x'}},{kind:'claim',payload:{subject:{type:'item',id:'x'},field:'name',value:'X',state:'current',authority:'human-canon'}}]});i.commit(b.id,{humanApproved:true});assert.equal(l.currentView({type:'item',id:'x'}).fields.name,'X')});
test('rejected intake remains preserved and never mutates graph',()=>{const {g,i}=load();const b=i.stage({source:{id:'old-design'},items:[{kind:'thing',payload:{type:'reward',id:'old'}}]});i.reject(b.id,{reviewer:'human',notes:'not current'});assert.equal(i.get(b.id).status,'rejected');assert.equal(g.getThing('reward','old'),null)});
