import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
function load(){const window={};const context=vm.createContext({window,structuredClone,console,globalThis:null});context.globalThis=context;for(const file of ['../engine/record-store-engine.js','../emojeo-emoji-record.js'])vm.runInContext(fs.readFileSync(new URL(file,import.meta.url),'utf8'),context,{filename:file});return{model:context.emojeoEmojiRecord||window.emojeoEmojiRecord,records:context.reusableRecordStore||window.reusableRecordStore}}
test('emoji record derives stable code-point identity without seeding content',()=>{const {model}=load();const r=model.normalize({glyph:'😀'});assert.equal(r.id,'U+1F600');assert.deepEqual([...r.codePoints],['U+1F600']);assert.equal(r.analysis.state,'unanalysed');assert.deepEqual([...r.names.aliases],[])});
test('emoji record keeps official taxonomy separate from evolving descriptions and analysis',()=>{const {model}=load();const r=model.normalize({glyph:'🦄',names:{cldr:'unicorn'},taxonomy:{group:'Animals & Nature',subgroup:'animal-mammal'},descriptions:{human:'A unicorn head'},analysis:{state:'reviewed',metadata:{run:'x'}}});assert.equal(r.taxonomy.group,'Animals & Nature');assert.equal(r.descriptions.human,'A unicorn head');assert.equal(r.analysis.state,'reviewed');assert.equal(r.analysis.metadata.run,'x')});
test('emoji record deliberately does not embed classifications or tag vocabulary',()=>{const {model}=load();const r=model.normalize({glyph:'💜'});assert.equal(Object.hasOwn(r,'tags'),false);assert.equal(Object.hasOwn(r,'classifications'),false);assert.ok(Array.isArray(r.relationships))});
test('emoji records use StringBoard record persistence with provenance and history',async()=>{const {model}=load();const store=model.createStore();await store.initialize();const saved=await store.put(model.toStoreRecord({glyph:'😀',names:{cldr:'grinning face'}},{status:'draft',provenance:{source:'test'}}));assert.equal(saved.metadata.recordType,'emoji');assert.equal(saved.data.names.cldr,'grinning face');assert.equal(saved.provenance.source,'test');await store.patch(saved.id,{data:{...saved.data,descriptions:{...saved.data.descriptions,human:'A broad smile'}}});assert.equal(store.get(saved.id).data.descriptions.human,'A broad smile');assert.equal(store.history({recordId:saved.id}).length,2)});
