import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import fs from 'node:fs';
const load=()=>{const c={structuredClone};c.globalThis=c;for(const f of ['emojeo-design-graph.js','emojeo-design-catalog.js','emojeo-canon-ledger.js','emojeo-progression-analysis.js','emojeo-design-health.js'])vm.runInNewContext(fs.readFileSync(f,'utf8'),c);return c};
function fixture(){const c=load(),g=c.emojeoDesignGraph.createDesignGraph();c.emojeoDesignCatalog.installDesignCatalog(g);for(const x of [{type:'event',id:'start'},{type:'achievement',id:'a'},{type:'gem',id:'g'},{type:'setting',id:'s'},{type:'reward',id:'orphan'}])c.emojeoDesignCatalog.createCatalogThing(g,x);const rel=(type,from,to)=>c.emojeoDesignCatalog.connect(g,{type,from,to,advisory:false,humanApproved:true});rel('progresses',{type:'event',id:'start'},{type:'achievement',id:'a'});rel('awards',{type:'achievement',id:'a'},{type:'gem',id:'g'});rel('unlocks',{type:'gem',id:'g'},{type:'setting',id:'s'});const p=c.emojeoProgressionAnalysis.createProgressionAnalysis({graph:g}),l=c.emojeoCanonLedger.createCanonLedger(g),h=c.emojeoDesignHealth.createDesignHealth({graph:g,catalog:c.emojeoDesignCatalog,progression:p,ledger:l});return {c,g,p,l,h,rel}}
test('design health combines catalog and progression findings',()=>{const {h}=fixture();const f=h.findings();assert.ok(f.some(x=>x.kind==='no-source'));assert.ok(f.some(x=>x.kind==='unreachable'))});
test('design health is read only',()=>{const {g,h}=fixture();const before=JSON.stringify(g.snapshot());h.report();assert.equal(JSON.stringify(g.snapshot()),before);assert.equal(h.report().policy.noAutomaticFixes,true)});
test('domain coverage reports empty and populated domains',()=>{const {h}=fixture();const d=h.domainCoverage();assert.equal(d.find(x=>x.id==='event').status,'connected');assert.equal(d.find(x=>x.id==='npc').status,'empty')});
test('canon conflicts become critical findings',()=>{const {l,h}=fixture();l.assertClaim({subject:{type:'gem',id:'g'},field:'name',value:'One',state:'proposed',authority:'curated'});l.assertClaim({subject:{type:'gem',id:'g'},field:'name',value:'Two',state:'proposed',authority:'curated'});assert.ok(h.findings().some(x=>x.kind==='canon-conflict'&&x.severity==='critical'))});
test('dependency cycles become critical findings',()=>{const {rel,h}=fixture();rel('depends-on',{type:'achievement',id:'a'},{type:'gem',id:'g'});rel('depends-on',{type:'gem',id:'g'},{type:'achievement',id:'a'});assert.ok(h.findings().some(x=>x.kind==='dependency-cycle'&&x.severity==='critical'))});
test('attention queue places critical findings first',()=>{const {l,h}=fixture();l.assertClaim({subject:{type:'gem',id:'g'},field:'x',value:1,state:'proposed',authority:'curated'});l.assertClaim({subject:{type:'gem',id:'g'},field:'x',value:2,state:'proposed',authority:'curated'});assert.equal(h.attentionQueue()[0].severity,'critical')});
test('inspectThing focuses findings on one graph thing',()=>{const {h}=fixture();const f=h.inspectThing({type:'reward',id:'orphan'});assert.ok(f.length);assert.ok(f.every(x=>(x.thing&&x.thing.id==='orphan')||(x.subject&&x.subject.id==='orphan')||(x.things||[]).some(t=>t.id==='orphan')))});
test('report summarizes severity counts and domains',()=>{const {h}=fixture();const r=h.report();assert.equal(r.kind,'emojeo-design-health-report');assert.equal(r.total,r.findings.length);assert.equal(r.domains.length,12);assert.equal(r.policy.advisoryProgressionExcludedByDefault,true)});
