import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
function load(){const ctx={structuredClone,Date,Map,Set,console};ctx.globalThis=ctx;ctx.window=ctx;vm.createContext(ctx);vm.runInContext(fs.readFileSync('emojeo-design-graph.js','utf8'),ctx);vm.runInContext(fs.readFileSync('emojeo-design-catalog.js','utf8'),ctx);const g=ctx.emojeoDesignGraph.createDesignGraph();ctx.emojeoDesignCatalog.installDesignCatalog(g);return {g,c:ctx.emojeoDesignCatalog};}
test('Pass 11 registers the initial MASHPEDITION design domains',()=>{const {g}=load();const ids=g.snapshot().types.map(x=>x.id);for(const id of ['emoji','mosaic','gem','setting','unlockable','achievement','trophy','metric','reward','item','npc','event'])assert.ok(ids.includes(id),id)});
test('catalog domains stay minimal and do not invent game content',()=>{const {g}=load();assert.equal(g.listThings().length,0)});
test('catalog creates typed Things in the shared graph',()=>{const {g,c}=load();const x=c.createCatalogThing(g,{type:'gem',id:'g1',name:'Test Gem'});assert.equal(x.type,'gem');assert.equal(x.metadata.catalogDomain,'gem')});
test('common design relationships connect domains without hardcoded endpoints',()=>{const {g,c}=load();c.createCatalogThing(g,{type:'gem',id:'g'});c.createCatalogThing(g,{type:'setting',id:'s'});const r=c.connect(g,{type:'unlocks',from:{type:'gem',id:'g'},to:{type:'setting',id:'s'},advisory:false,humanApproved:true});assert.equal(r.type,'unlocks')});
test('machine-suggested catalog connections remain advisory',()=>{const {g,c}=load();c.createCatalogThing(g,{type:'item',id:'a'});c.createCatalogThing(g,{type:'event',id:'b'});const r=c.connect(g,{type:'associated-with',from:{type:'item',id:'a'},to:{type:'event',id:'b'}});assert.equal(r.advisory,true)});
test('domain summary reports counts, connections, and disconnected Things',()=>{const {g,c}=load();c.createCatalogThing(g,{type:'gem',id:'a'});c.createCatalogThing(g,{type:'gem',id:'b'});const s=c.domainSummary(g).find(x=>x.id==='gem');assert.equal(s.count,2);assert.equal(s.disconnected,2)});
test('gap analysis finds rewards or Gems with no source',()=>{const {g,c}=load();c.createCatalogThing(g,{type:'gem',id:'lonely'});assert.ok(c.findGaps(g).some(x=>x.kind==='no-source'&&x.thing.id==='lonely'))});
test('gap analysis can identify an unused metric',()=>{const {g,c}=load();c.createCatalogThing(g,{type:'metric',id:'visits'});assert.ok(c.findGaps(g).some(x=>x.kind==='unused-metric'&&x.thing.id==='visits'))});
