import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
const root=new URL('../',import.meta.url);const ctx=vm.createContext({structuredClone,console});for(const f of ['emojeo-design-graph.js','emojeo-design-catalog.js','emojeo-canon-ledger.js','emojeo-progression-analysis.js','emojeo-design-health.js','emojeo-change-impact.js'])vm.runInContext(fs.readFileSync(new URL(f,root),'utf8'),ctx);
function setup(){const catalog=ctx.emojeoDesignCatalog;const graph=ctx.emojeoDesignGraph.createDesignGraph();catalog.installDesignCatalog(graph);for(const [type,id] of [['event','e1'],['achievement','a1'],['gem','g1'],['setting','s1']])graph.createThing({type,id,name:id});graph.relate({type:'progresses',from:{type:'event',id:'e1'},to:{type:'achievement',id:'a1'},advisory:false,humanApproved:true});graph.relate({type:'awards',from:{type:'achievement',id:'a1'},to:{type:'gem',id:'g1'},advisory:false,humanApproved:true});graph.relate({type:'unlocks',from:{type:'gem',id:'g1'},to:{type:'setting',id:'s1'},advisory:false,humanApproved:true});const ledger=ctx.emojeoCanonLedger.createCanonLedger(graph);const progression=ctx.emojeoProgressionAnalysis.createProgressionAnalysis({graph});const health=ctx.emojeoDesignHealth.createDesignHealth({graph,catalog,progression,ledger});return {graph,ledger,progression,health,impact:ctx.emojeoChangeImpact.createChangeImpact({graph,ledger,progression,health})}}
test('traces downstream and upstream connected impact',()=>{const {impact}=setup();const a=impact.affectedThings({type:'achievement',id:'a1'});assert.equal(a.length,3);assert.ok(a.some(x=>x.thing.id==='s1'))});
test('advisory edges excluded by default',()=>{const {graph,impact}=setup();graph.relate({type:'associated-with',from:{type:'setting',id:'s1'},to:{type:'event',id:'e1'},advisory:true});const a=impact.affectedThings({type:'setting',id:'s1'});assert.equal(a.filter(x=>x.via.advisory).length,0)});
test('advisory edges can be included explicitly',()=>{const {graph,impact}=setup();graph.relate({type:'associated-with',from:{type:'setting',id:'s1'},to:{type:'event',id:'e1'},advisory:true});const a=impact.affectedThings({type:'setting',id:'s1'},{includeAdvisory:true});assert.ok(a.some(x=>x.via.advisory))});
test('retirement preview warns about connected content',()=>{const {impact}=setup();const p=impact.propose({kind:'retire-thing',subject:{type:'gem',id:'g1'}});assert.ok(p.warnings.some(w=>w.kind==='connected-content'))});
test('retirement preview sees current canon claims',()=>{const {ledger,impact}=setup();ledger.assertClaim({subject:{type:'gem',id:'g1'},field:'color',value:'blue',state:'current',authority:'human-canon'});const p=impact.propose({kind:'retire-thing',subject:{type:'gem',id:'g1'}});assert.ok(p.warnings.some(w=>w.kind==='current-canon-on-subject'))});
test('claim change surfaces existing claims',()=>{const {ledger,impact}=setup();ledger.assertClaim({subject:{type:'setting',id:'s1'},field:'unlock',value:'old',state:'historical',authority:'human-canon'});const p=impact.propose({kind:'change-claim',subject:{type:'setting',id:'s1'},field:'unlock',value:'new'});assert.ok(p.warnings.some(w=>w.kind==='existing-claims'))});
test('preview explicitly cannot mutate graph or canon',()=>{const {graph,ledger,impact}=setup();const beforeG=JSON.stringify(graph.snapshot()),beforeL=JSON.stringify(ledger.snapshot());const p=impact.propose({kind:'retire-thing',subject:{type:'achievement',id:'a1'}});assert.equal(p.policy.mutatesGraph,false);assert.equal(p.policy.mutatesCanon,false);assert.equal(JSON.stringify(graph.snapshot()),beforeG);assert.equal(JSON.stringify(ledger.snapshot()),beforeL)});
test('unknown subjects and unsupported changes are rejected',()=>{const {impact}=setup();assert.throws(()=>impact.propose({kind:'retire-thing',subject:{type:'gem',id:'missing'}}));assert.throws(()=>impact.propose({kind:'silently-fix',subject:{type:'gem',id:'g1'}}))});
