import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import fs from 'node:fs';
const load=f=>{const c={structuredClone};c.globalThis=c;vm.runInNewContext(fs.readFileSync(f,'utf8'),c);return c};
function fixture(){const c=load('emojeo-design-graph.js');vm.runInNewContext(fs.readFileSync('emojeo-design-catalog.js','utf8'),c);vm.runInNewContext(fs.readFileSync('emojeo-progression-analysis.js','utf8'),c);const g=c.emojeoDesignGraph.createDesignGraph();c.emojeoDesignCatalog.installDesignCatalog(g);for(const x of [{type:'event',id:'start'},{type:'achievement',id:'a'},{type:'gem',id:'g'},{type:'setting',id:'s'},{type:'reward',id:'orphan'}])c.emojeoDesignCatalog.createCatalogThing(g,x);const rel=(type,from,to)=>c.emojeoDesignCatalog.connect(g,{type,from,to,advisory:false,humanApproved:true});rel('progresses',{type:'event',id:'start'},{type:'achievement',id:'a'});rel('awards',{type:'achievement',id:'a'},{type:'gem',id:'g'});rel('unlocks',{type:'gem',id:'g'},{type:'setting',id:'s'});return {g,a:c.emojeoProgressionAnalysis.createProgressionAnalysis({graph:g}),rel,c};}
test('progression analysis is read only and excludes advisory edges by default',()=>{const {g,a,c}=fixture();c.emojeoDesignCatalog.connect(g,{type:'unlocks',from:{type:'event',id:'start'},to:{type:'reward',id:'orphan'},advisory:true});assert.equal(a.network().edges.length,3);assert.equal(a.network({includeAdvisory:true}).edges.length,4);assert.equal(a.report().policy.noCanonMutation,true)});
test('finds roots and sinks',()=>{const {a}=fixture();assert.ok(a.roots().some(x=>x.id==='start'));assert.ok(a.sinks().some(x=>x.id==='s'))});
test('traces multi-hop progression paths',()=>{const {a}=fixture();const p=a.paths({type:'event',id:'start'},{type:'setting',id:'s'});assert.equal(p.length,1);assert.equal(p[0].things.length,4)});
test('finds unreachable content from source domains',()=>{const {a}=fixture();assert.ok(a.unreachable().some(x=>x.id==='orphan'))});
test('requirement relationships reverse into prerequisite flow',()=>{const {g,a,c}=fixture();c.emojeoDesignCatalog.connect(g,{type:'requires',from:{type:'setting',id:'s'},to:{type:'gem',id:'g'},advisory:false,humanApproved:true});const n=a.network();assert.ok(n.edges.some(e=>e.from==='gem:g'&&e.to==='setting:s'&&e.semantic==='requirement'))});
test('detects dependency cycles without changing graph',()=>{const {g,a,c}=fixture();c.emojeoDesignCatalog.connect(g,{type:'depends-on',from:{type:'achievement',id:'a'},to:{type:'gem',id:'g'},advisory:false,humanApproved:true});c.emojeoDesignCatalog.connect(g,{type:'depends-on',from:{type:'gem',id:'g'},to:{type:'achievement',id:'a'},advisory:false,humanApproved:true});assert.ok(a.cycles().length>=1);assert.equal(g.getThing('gem','g').id,'g')});
test('identifies bottlenecks by dependent count',()=>{const {g,a,c}=fixture();c.emojeoDesignCatalog.createCatalogThing(g,{type:'reward',id:'r2'});c.emojeoDesignCatalog.connect(g,{type:'awards',from:{type:'achievement',id:'a'},to:{type:'reward',id:'r2'},advisory:false,humanApproved:true});assert.ok(a.bottlenecks({minimumDependents:2}).some(x=>x.thing.id==='a'))});
test('report combines progression diagnostics',()=>{const {a}=fixture();const r=a.report();assert.equal(r.kind,'emojeo-progression-report');assert.equal(r.nodeCount,5);assert.ok(Array.isArray(r.unreachable));assert.ok(Array.isArray(r.cycles))});
