import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
const root=new URL('../',import.meta.url),ctx=vm.createContext({structuredClone,console,Date});for(const f of ['emojeo-design-graph.js','emojeo-design-catalog.js','emojeo-design-workbench.js'])vm.runInContext(fs.readFileSync(new URL(f,root),'utf8'),ctx);
function setup(){const graph=ctx.emojeoDesignGraph.createDesignGraph();ctx.emojeoDesignCatalog.installDesignCatalog(graph);graph.createThing({type:'gem',id:'ruby',name:'Ruby Gem'});graph.createThing({type:'setting',id:'cellar',name:'Color Cellar'});graph.createThing({type:'npc',id:'aunt',name:'Aunt Cillary',status:'draft'});graph.relate({id:'unlock',type:'unlocks',from:{type:'gem',id:'ruby'},to:{type:'setting',id:'cellar'},advisory:false,humanApproved:true});return {graph,wb:ctx.emojeoDesignWorkbench.createDesignWorkbench({graph,catalog:ctx.emojeoDesignCatalog})}}
test('workbench summarizes every registered domain without inventing content',()=>{const {wb}=setup();const s=wb.summary();assert.equal(s.total,3);assert.ok(s.domains.some(d=>d.id==='gem'&&d.count===1));assert.ok(s.domains.some(d=>d.id==='trophy'&&d.count===0))});
test('domain, status, and text filters compose',()=>{const {wb}=setup();wb.setFilters({domain:'npc',status:'draft',query:'cill'});assert.equal([...wb.rows()].map(x=>x.id).join(','),'aunt')});
test('rows expose connection counts without changing the graph',()=>{const {graph,wb}=setup();const before=JSON.stringify(graph.snapshot());assert.equal(wb.rows().find(x=>x.id==='ruby').connectionCount,1);assert.equal(JSON.stringify(graph.snapshot()),before)});
test('selection inspects connected Things in either direction',()=>{const {wb}=setup();const d=wb.select('setting','cellar');assert.equal(d.thing.name,'Color Cellar');assert.equal(d.connections[0].other.name,'Ruby Gem')});
test('render provides a practical multi-domain browser surface',()=>{const {wb}=setup();wb.select('gem','ruby');const html=wb.render();assert.match(html,/MASHPEDITION Design Workbench/);assert.match(html,/Ruby Gem/);assert.match(html,/Color Cellar/)});
test('exported workbench view is explicitly read-only',()=>{const {wb}=setup();const out=wb.exportView();assert.equal(out.kind,'emojeo-design-workbench-view');assert.equal(out.policy.readOnly,true);assert.equal(out.policy.doesNotMutateCanon,true)});
