import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
const root=new URL('../',import.meta.url),ctx=vm.createContext({structuredClone,console,Date});for(const f of ['emojeo-design-graph.js','emojeo-design-catalog.js','emojeo-design-workbench.js','emojeo-design-operations.js'])vm.runInContext(fs.readFileSync(new URL(f,root),'utf8'),ctx);
function setup(){const graph=ctx.emojeoDesignGraph.createDesignGraph();ctx.emojeoDesignCatalog.installDesignCatalog(graph);graph.createThing({type:'gem',id:'ruby',name:'Ruby'});const wb=ctx.emojeoDesignWorkbench.createDesignWorkbench({graph,catalog:ctx.emojeoDesignCatalog});const health={report:()=>({findings:[{kind:'unreachable',severity:'warning',thing:{type:'gem',id:'ruby',name:'Ruby'}}]})};const decisions={list:()=>[{id:'d1',title:'Choose unlock',state:'review'},{id:'d2',title:'Old choice',state:'implemented'}]};const reconciliation={list:()=>[{id:'r1',items:[{id:'i1',status:'unresolved',payload:{name:'Color Cellar'},conflicts:[{kind:'name'}]},{id:'i2',status:'resolved',payload:{name:'Done'},conflicts:[]}]}]};return ctx.emojeoDesignOperations.createDesignOperations({workbench:wb,health,decisions,reconciliation})}
test('operations queue combines only open actionable work',()=>{const ops=setup();assert.equal(ops.queue().length,3);assert.ok(ops.queue().some(x=>x.kind==='decision-review'));assert.ok(!ops.queue().some(x=>x.label==='Old choice'))});
test('higher-risk health and import conflicts sort ahead of ordinary review',()=>{const q=setup().queue();assert.equal(q[0].priority,'warning');assert.equal(q[1].priority,'warning');assert.equal(q[2].priority,'review')});
test('source filter preserves operational boundaries',()=>{const ops=setup();assert.equal(ops.queue({source:'decision'}).length,1);assert.equal(ops.queue({source:'reconciliation'}).length,1)});
test('summary joins operational workload with design inventory',()=>{const s=setup().summary();assert.equal(s.open,3);assert.equal(s.design.total,1);assert.deepEqual({...s.bySource},{health:1,decision:1,reconciliation:1})});
test('inspect returns queue evidence without executing an action',()=>{const ops=setup(),item=ops.queue().find(x=>x.source==='decision'),before=JSON.stringify(ops.queue());assert.equal(ops.inspect(item.id).action,'human-decision');assert.equal(JSON.stringify(ops.queue()),before)});
test('export and render explicitly preserve human-controlled read-only coordination',()=>{const ops=setup(),out=ops.exportQueue();assert.equal(out.policy.readOnly,true);assert.equal(out.policy.mutatesCanon,false);assert.match(ops.render(),/MASHPEDITION Design Operations/)});
