import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
const root=new URL('../',import.meta.url);const ctx=vm.createContext({structuredClone,console});for(const f of ['emojeo-design-graph.js','emojeo-design-catalog.js','emojeo-canon-ledger.js','emojeo-progression-analysis.js','emojeo-design-health.js','emojeo-change-impact.js','emojeo-decision-workspace.js'])vm.runInContext(fs.readFileSync(new URL(f,root),'utf8'),ctx);
function setup(){const graph=ctx.emojeoDesignGraph.createDesignGraph();ctx.emojeoDesignCatalog.installDesignCatalog(graph);graph.createThing({type:'gem',id:'g1',name:'Gem'});graph.createThing({type:'setting',id:'s1',name:'Setting'});graph.relate({type:'unlocks',from:{type:'gem',id:'g1'},to:{type:'setting',id:'s1'},advisory:false,humanApproved:true});const ledger=ctx.emojeoCanonLedger.createCanonLedger(graph);const progression=ctx.emojeoProgressionAnalysis.createProgressionAnalysis({graph});const health=ctx.emojeoDesignHealth.createDesignHealth({graph,catalog:ctx.emojeoDesignCatalog,progression,ledger});const impact=ctx.emojeoChangeImpact.createChangeImpact({graph,ledger,progression,health});return {graph,ledger,ws:ctx.emojeoDecisionWorkspace.createDecisionWorkspace({impact})}}
const change={kind:'retire-thing',subject:{type:'gem',id:'g1'}};
test('draft captures a real impact preview',()=>{const {ws}=setup();const d=ws.create({title:'Retire Gem',change});assert.equal(d.state,'draft');assert.equal(d.preview.policy.previewOnly,true);assert.ok(d.preview.affected.length)});
test('decision requires title and valid impact change',()=>{const {ws}=setup();assert.throws(()=>ws.create({change}));assert.throws(()=>ws.create({title:'Bad',change:{kind:'nope',subject:{type:'gem',id:'g1'}}}))});
test('review is an explicit lifecycle step',()=>{const {ws}=setup();const d=ws.create({title:'Retire Gem',change});assert.equal(ws.submit(d.id,{actor:'Billy'}).state,'review');assert.throws(()=>ws.submit(d.id,{actor:'Billy'}))});
test('approval requires explicit human actor',()=>{const {ws}=setup();const d=ws.create({title:'Retire Gem',change});ws.submit(d.id);assert.throws(()=>ws.decide(d.id,{approved:true,actor:'machine'}));assert.equal(ws.decide(d.id,{approved:true,actor:'Billy'}).state,'approved')});
test('rejection is preserved rather than deleted',()=>{const {ws}=setup();const d=ws.create({title:'Retire Gem',change});ws.submit(d.id);ws.decide(d.id,{approved:false,actor:'Billy',note:'Keep it'});assert.equal(ws.get(d.id).state,'rejected');assert.equal(ws.list({state:'rejected'}).length,1)});
test('approved decision creates plan but does not mutate graph or canon',()=>{const {graph,ledger,ws}=setup();const bg=JSON.stringify(graph.snapshot()),bl=JSON.stringify(ledger.snapshot());const d=ws.create({title:'Retire Gem',change});ws.submit(d.id);ws.decide(d.id,{approved:true,actor:'Billy'});const p=ws.implementationPlan(d.id);assert.equal(p.policy.planOnly,true);assert.equal(p.policy.autoMutatesGraph,false);assert.equal(JSON.stringify(graph.snapshot()),bg);assert.equal(JSON.stringify(ledger.snapshot()),bl)});
test('unapproved decisions cannot produce implementation plans',()=>{const {ws}=setup();const d=ws.create({title:'Retire Gem',change});assert.throws(()=>ws.implementationPlan(d.id))});
test('implemented state requires approved decision and human confirmation',()=>{const {ws}=setup();const d=ws.create({title:'Retire Gem',change});assert.throws(()=>ws.markImplemented(d.id,{actor:'Billy'}));ws.submit(d.id);ws.decide(d.id,{approved:true,actor:'Billy'});assert.throws(()=>ws.markImplemented(d.id,{actor:'system'}));assert.equal(ws.markImplemented(d.id,{actor:'Billy'}).state,'implemented')});
